### PR TITLE
Fix encoding detection

### PR DESCRIPTION
**Pull request by 07pepa**

### CODE REVIEW

**Comment by 07pepa** [comment]
it is unclear why only one test fails

**Comment by lemonyte** [comment]
Would it not be easier to just open all files with `utf-8` encoding instead of adding a dependency on `chardet`? See PR #85.

> it is unclear why only one test fails

I have this same issue on my local machine, no clue what's causing it.

**Comment by 07pepa** [comment]
@lemonyte your code does  the business as well

**Comment by 07pepa** [comment]
so i close this pr

**Pull request closed without merging**
